name: "Podcast Generator"
author: "Zanotelli"
description: "Gera um feed para um podcast por um arquivo YAML"
runs:
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git-branch"
  color: "blue"
inputs: 
  email:
    description: Email do desenvolvedor
    required: true
    default: ${{ github.actor}}@localhost
  name:
    description: Nome do desenvolvedor
    required: true
    default: ${{ github.actor }}